:hammer: Add jest configuration.
To suppress the following error messages:

```
    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/en/ecmascript-modules for how to enable it.
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/gongo/Workspaces/src/github.com/gongo/react-hook-figlet/node_modules/figlet/importable-fonts/Standard.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export default `flf2a$ 6 5 16 15 13 0 24463 229
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      29 |     }
      30 |
    > 31 |     import(`figlet/importable-fonts/${font}.js`).then((module: { default: string }): void => {
         |     ^
      32 |       figlet.parseFont(font, module.default)
```